# vim: set sw=4 sts=4 et tw=0 ft=bash :

halt
return_void     dense_dense_float_sum                       dense_dense_float_sum
return_void     dense_sparse_float_sum                      dense_sparse_float_sum
return_dword    dense_dense_float_dot_product               dense_dense_float_dot_product
return_void     dense_dense_float_element_product           dense_dense_float_element_product
return_void     dense_dense_float_matrix_vector_product     dense_dense_float_matrix_vector_product
return_void     dense_dense_float_matrix_product            dense_dense_float_matrix_product
return_dword    dense_float_vector_reduction_sum            dense_float_vector_reduction_sum
return_void     dense_float_scale                           dense_float_scale
