#!/usr/bin/env bash

taubase=0.50
for i in {1..151}
do
    cp honei.tq honei.tq.tmp
    tau=$(echo scale=5\;$taubase+0.01|bc)
    taubase=${tau}
    sed "s/TAU/${tau}/g" <honei.tq.tmp >honei.tq.tmp2
    mv honei.tq.tmp2 honei.tq.tmp
    qsub honei.tq.tmp
    #echo $tau
done
rm -f honei.tq.tmp
