      INTERFACE
      SUBROUTINE MVUCSR1_F90(M,IA,JA,A,X,Y)
      INTEGER M
      INTEGER, POINTER :: IA(:),JA(:)
      DOUBLE PRECISION, POINTER :: A(:)
      DOUBLE PRECISION X(*),Y(*)
      END
      END INTERFACE
