      INTERFACE
      SUBROUTINE TVUCSR1_F90(M,N,IA,JA,A,X,Y)
      INTEGER M,N
      INTEGER, POINTER :: IA(:),JA(:)
      DOUBLE PRECISION, POINTER :: A(:)
      DOUBLE PRECISION X(*),Y(*)
      END
      END INTERFACE
