# vim: set sw=4 sts=4 et tw=0 ft=bash :

halt

# UnitTest operations
#####################
void            test_instruction_finished     test_instruction_finished
dword           test_result_dword             test_result_dword
qword           test_result_qword             test_result_qword

inline_function "void" test_instruction_finished << inline_function_end
    return;
inline_function_end

inline_function "unsigned" test_result_dword << inline_function_end
    return 0x12345678;
inline_function_end

inline_function "unsigned long long" test_result_qword << inline_function_end
    return 0x123456789ABCDEF0ll;
inline_function_end
