#!/usr/bin/env bash
for ((i = 1 ; i <=128 ; i*=2))
do
    cp honei.tq honei.tq.tmp
    sed "s/PROC/${i}/g" <honei.tq.tmp >honei.tq.tmp2
    mv honei.tq.tmp2 honei.tq.tmp
    qsub honei.tq.tmp
done
rm -f honei.tq.tmp
