#!/usr/bin/env bash
for ((i = 4 ; i <=128 ; i*=2))
do
    cp honei.tq honei.tq.tmp
    j=$((${i}/4))
    sed "s/PROC/${i}/g" <honei.tq.tmp >honei.tq.tmp2
    sed "s/NODES/${j}/g" <honei.tq.tmp2 >honei.tq.tmp3
    mv honei.tq.tmp3 honei.tq.tmp
    qsub honei.tq.tmp
done
rm -f honei.tq.tmp
rm -f honei.tq.tmp2
rm -f honei.tq.tmp3
